id: A67BD72B7
title: Prayer to the Lineage of Seven-Point Mind Training
type: translation
pechas:
- I54243F4E
- I3D2411C0
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:58:59.938355
  last_modified_at: 2023-01-04 11:58:59.938364
  collections:
  - Gyalse Tokme Zangpo
  - Works of Tibetan Masters
alignment_to_base:
  I54243F4E/0610: 83FF
  I3D2411C0/FD3F: 83FF
